let tapeMap;
let gameSetup;
let homeScreen;
let homeStory;
let timer;
let game;
let font;
let font8bit;
let referenceButton;
let managerButton;
let restartButton;
let homeScreenImage;
let sceneryImage;
let scenario;
let gameOverImage;
let createNewElement;
let life;
let heartImage;
let heartItem;
let scores;
let homeWitchImage;
let homeWitch;
let mainCharacterImage;
let mainCharacter;
let dropEnemyImage;
let flyingDropEnemyImage;
let trollEnemyImage;
let bulbasaurImage;
let pikachuImage;
let umbreonImage;
let charmanderImage;
let soundtrack;
let jumpSound;
let currentScene = 'homeScreen';
let allScenes;
const enemiesArray = [];
const pokemonArray = [];

const gameStoryText = 'Os humanos descobriram a existência das bruxas há 100 anos atrás e desde então procuram um meio de exterminá-las. Um cientista descobriu um vírus que tem origem em um animal exótico e que só se propaga entre as bruxas. Ele enganou uma bruxinha lhe dando uma maçã contaminada. O vírus começou a se espalhar e o objetivo da bruxinha Hipsta agora é vencer os monstros da floresta sombria e encontrar Chronus o único mago capaz de criar uma vacina.';